### ISSUE TITLE
Cursor color in solarized light hides the underlaying character.

### ISSUE THREAD

**Issue by DavyLandman** [tomislav/osx-terminal.app-colors-solarized#10]
Yosemite Terminal.app:
![screen shot 2015-01-27 at 10 12 12](https://cloud.githubusercontent.com/assets/179603/5916054/021d0c04-a60d-11e4-9a7d-569eec2b4d64.png)

MacVim solarized (from original repo):
![screen shot 2015-01-27 at 10 14 56](https://cloud.githubusercontent.com/assets/179603/5916088/60ec9a92-a60d-11e4-8e9c-2be234dede0c.png)

iTerm2 solarized (from original repo):
![screen shot 2015-01-27 at 10 14 18](https://cloud.githubusercontent.com/assets/179603/5916079/465291f0-a60d-11e4-8ed8-a4c3b85c3da6.png)

I think the text font is perhaps to light?

**Comment by tomislav** [comment]
Terminal.app doesn't support inverting the color of the text behind the cursor. You can use a different cursor if it bothers you.
